// 属灵塑造模块的中文内容数据 / Chinese content data for Spiritual Formation.
// 数组字段按「索引」与 data/sinPatterns.ts 的英文数组逐项对齐。
// 缺失项由 localize.js 的 pickVal 优雅回退英文。

export const PATTERN_ZH = {
  self_centeredness: {
    name: "自我中心", shortName: "自我",
    description: "活得仿佛我的生命主要属于自己，而非属于神。",
    biblicalDiagnosis: "自我中心是旧人把个人的欲望、安逸、掌控、名声和自主放在中心，取代了神的荣耀与旨意。",
    coreLie: "我的生命属于我自己，我有权决定什么对我才是好的。",
    gospelTruth: "我已经与基督同钉十字架；现在活着的不再是我，乃是基督在我里面活着。",
    repentancePrayer: "主耶稣，我承认我常常活得好像我属于自己。我把自己的安逸、计划和掌控放在中心。求你赦免我。教我今天舍己，背起十字架来跟从你。",
    commonSymptoms: ["我抗拒被打断。", "当我的计划受阻时我会发怒。", "我利用别人达成自己的目标。", "我主要在需要帮助时才祷告。", "我先问对我有何益处，才问什么能荣耀神。", "我觉得自己理当享有安逸、被肯定或掌控。"],
    deepIdols: ["掌控", "自主", "安逸", "名声", "个人成功"],
    putOffActions: ["不再只凭个人方便做决定。", "不再把人当作达成目标的工具。", "不再把每个偏好都当作权利来维护。"],
    putOnActions: ["求问神今天的顺服是什么样子。", "不求被肯定地服事一个人。", "在祷告中把一个计划交托给神。"],
  },
  idolatry: {
    name: "拜偶像", shortName: "偶像",
    description: "把终极的信靠、爱、惧怕、盼望或身份给了受造之物，而非造物主。",
    biblicalDiagnosis: "拜偶像是用受造之物取代造物主，要它们承担终极的安全感、身份、喜乐或拯救之重担。",
    coreLie: "这受造之物能给我唯有神才能给的安全感、身份、喜乐或拯救。",
    gospelTruth: "神自己是我的产业、我的至宝、我的避难所和满溢的喜乐。",
    repentancePrayer: "父啊，我承认我爱受造之物、倚靠它们过于爱你、倚靠你。求你揭露我的偶像，恢复我的敬拜。教我的心说：唯独你是我的福分。",
    commonSymptoms: ["当重要的东西受威胁时我会惊慌。", "为了保住某物我会在顺服上妥协。", "我无法想象没有它还能快乐。", "我把生活围绕着它来安排。", "当神触碰它时我会发怒。"],
    deepIdols: ["金钱", "爱情", "成功", "儿女", "事业", "科技", "安逸", "认可", "国族", "美貌"],
    putOffActions: ["不再把受造之物当作终极。", "不再为保住偶像而牺牲顺服。", "不再用财物、地位或认可来衡量身份。"],
    putOnActions: ["在偶像最强之处特意敬拜神。", "操练感恩。", "藉祷告或慷慨释放一处执着。"],
  },
  greed_consumerism: {
    name: "贪婪与消费主义", shortName: "贪婪",
    description: "藉着更多金钱、财物、消费或财务掌控来寻求安全感、身份或满足。",
    biblicalDiagnosis: "贪婪把供应、积累和消费当作避难所，而非以神为父、为至宝来领受。",
    coreLie: "只要我拥有更多，我终将得着安全与满足。",
    gospelTruth: "我的父知道我所需要的。人的生命不在乎家道丰富。",
    repentancePrayer: "主啊，我承认我的贪婪和对匮乏的惧怕。我一直在金钱和财物里寻找安全感。教我知足、慷慨，并信靠你的供应。",
    commonSymptoms: ["我拿自己的财物或财富与人比较。", "我难以慷慨地给予。", "我靠购物来调节情绪。", "我执迷于财务上的获利。", "即使需用得着供应，我仍觉得贫穷。"],
    deepIdols: ["安全感", "财富", "地位", "掌控", "安逸"],
    putOffActions: ["停止冲动消费。", "停止比较财富。", "不再把金钱当作终极的安全感。"],
    putOnActions: ["慷慨地给予。", "操练感恩。", "在神面前作出消费的决定。"],
  },
  sexual_disorder: {
    name: "情欲失序", shortName: "纯洁",
    description: "在神为圣洁、盟约之爱与舍己纯洁所定的设计之外，使用身体、想象或他人。",
    biblicalDiagnosis: "情欲失序把欲望与圣洁、盟约之爱以及『身体属于基督』的真理割裂开来。",
    coreLie: "我的身体和欲望属于我自己，性的快感能医治、满足或定义我。",
    gospelTruth: "我的身体是圣灵的殿；我是重价买来的，所以要在身体上荣耀神。",
    repentancePrayer: "主啊，我承认我没有用身体、想象和欲望尊荣你。求你洁净我的心，教我视他人为神形象的承载者，全然属于你。",
    commonSymptoms: ["使用色情内容", "情欲的想象", "把他人物化", "隐秘的性行为", "藉亲密逃避孤独", "忽视神对身体的设计"],
    deepIdols: ["快感", "掌控", "安逸", "被肯定", "逃避", "权力"],
    putOffActions: ["移除引发性试探的来源。", "停止隐秘的模式。", "停止把他人物化。"],
    putOnActions: ["尊荣身体为属于基督。", "操练眼目的看守。", "若反复出现就寻求问责。"],
  },
  pride: {
    name: "骄傲", shortName: "骄傲",
    description: "藉着自觉优越、自我倚靠、自我防卫或拒绝被纠正，把自己高举在神和他人之上。",
    biblicalDiagnosis: "骄傲抗拒倚靠神，藉着维护优越、名声和自我作主，拒绝基督的谦卑。",
    coreLie: "我必须高人一等，我并不真正需要责备、怜悯或倚靠。",
    gospelTruth: "神赐恩给谦卑的人。我的价值不在于高人一等，而在于基督的怜悯。",
    repentancePrayer: "主啊，我承认我的骄傲、自高和抗拒责备。求你赐我基督谦卑自己的心，教我以需要恩典的罪人之心领受恩典。",
    commonSymptoms: ["自我防卫", "轻蔑", "无法道歉", "卖弄或自我炫耀", "看不起别人", "暗自认为自己更聪明或更好"],
    deepIdols: ["优越感", "名声", "能力", "被认可", "掌控"],
    putOffActions: ["停止自高的言语。", "停止对他人的轻蔑。", "停止抗拒被纠正。"],
    putOnActions: ["承认一处软弱。", "不加辩护地接受纠正。", "真诚地尊重另一个人。"],
  },
  lies_falsehood: {
    name: "谎言与虚假", shortName: "真实",
    description: "为保护自己、谋取好处、逃避羞耻或操控他人，而扭曲、隐藏、夸大、操纵或否认真相。",
    biblicalDiagnosis: "虚假弃绝了真理的神，藉着隐藏、经营形象、夸大或操纵来掌控现实。",
    coreLie: "真相太危险了，所以我必须经营现实来保护自己。",
    gospelTruth: "因为我在基督里被悦纳，我不再需要靠谎言而活。",
    repentancePrayer: "诚实的神啊，我承认我曾隐藏、扭曲或操纵真相。求真理进入我的内心，使我在你和人面前诚实。",
    commonSymptoms: ["夸大其词", "半真半假", "隐藏罪", "经营虚假形象", "操纵性的言语", "回避认罪"],
    deepIdols: ["自我保护", "被认可", "掌控", "名声", "害怕被揭露"],
    putOffActions: ["停止夸大。", "停止隐藏已知的罪。", "停止用言语操纵他人。"],
    putOnActions: ["用爱心说诚实话。", "诚实地认罪。", "在合宜处修补欺骗。"],
  },
  hatred_division: {
    name: "暴力、仇恨与分裂", shortName: "和睦",
    description: "在心思、言语或行为上对他人怀有愤怒、轻蔑、报复、残忍或制造分裂。",
    biblicalDiagnosis: "仇恨任凭愤怒长成轻蔑与报复，而不把伸冤交托给神、追求和睦。",
    coreLie: "我的愤怒足够正义，足以使轻蔑、报复或毁灭显得合理。",
    gospelTruth: "基督已经饶恕了我。我可以把伸冤交给神，并追求和睦。",
    repentancePrayer: "主啊，我承认我的愤怒、轻蔑和以恶报恶的心。你已经怜悯了我。教我饶恕、祝福并追求和睦。",
    commonSymptoms: ["苛刻的言语", "网络攻击", "轻蔑", "报复的幻想", "拒绝饶恕", "制造对立"],
    deepIdols: ["掌控", "没有怜悯的公义", "优越感", "受伤的自尊", "报复"],
    putOffActions: ["停止报复性的言语。", "停止反复演练报复。", "停止滋养轻蔑。"],
    putOnActions: ["为那人祷告。", "在智慧许可时寻求和好。", "温和地说话。"],
  },
  injustice_oppression: {
    name: "不义与压迫", shortName: "公义",
    description: "以权力、金钱、地位、制度或冷漠，去忽视、剥削或伤害软弱的人。",
    biblicalDiagnosis: "不义毫无怜悯地利用自己的优势，忘记了那位护卫软弱者的神。",
    coreLie: "我的好处比公义、怜悯和邻舍的益处更重要。",
    gospelTruth: "神喜爱公义，护卫软弱的人。在基督里，我蒙召去行怜悯与公义。",
    repentancePrayer: "公义与怜悯的神啊，我承认我在哪里忽视或参与了不公。教我行公义，好怜悯，存谦卑的心与你同行。",
    commonSymptoms: ["忽视弱势者", "剥削工人或下属", "为私利使用权力", "对苦难漠不关心", "不公平的对待", "选择性的公义"],
    deepIdols: ["权力", "利润", "安逸", "地位", "部落式的忠诚"],
    putOffActions: ["不再心安理得地从不公中得益。", "不再忽视软弱的人。", "不再为私利使用权力。"],
    putOnActions: ["护卫弱势者。", "操练公平的待人。", "付出时间或资源去行怜悯。"],
  },
  religious_hypocrisy: {
    name: "宗教伪善", shortName: "真诚",
    description: "在内心仍然骄傲、冷漠、虚假或不肯悔改时，维持敬虔的外表。",
    biblicalDiagnosis: "宗教伪善维持着令人印象深刻的属灵外表，却回避内里的真实、谦卑、爱与悔改。",
    coreLie: "只要我看起来属灵，我就不必在神面前被真正揭露和改变。",
    gospelTruth: "神所要的是内里的诚实，基督接纳诚实的罪人。",
    repentancePrayer: "主啊，求你鉴察我、认识我。我承认我会在隐藏骄傲与罪的同时显得属灵。使我在你面前真实，而非只在人前光鲜。",
    commonSymptoms: ["为别人表演属灵", "躲在事奉背后隐藏罪", "有正确教义却没有爱", "苛刻地论断他人", "没有诚实的祷告", "没有谦卑的服事"],
    deepIdols: ["名声", "宗教地位", "掌控", "优越感", "被认可"],
    putOffActions: ["停止表演属灵。", "停止用教义来回避悔改。", "停止藉论断他人来显得自己公义。"],
    putOnActions: ["诚实地祷告。", "坦白隐藏的动机。", "在无人看见处服事。"],
  },
  coldness_lack_of_love: {
    name: "冷漠与缺乏爱", shortName: "爱",
    description: "藉着冷漠或自我保护，向神和邻舍收回爱、怜悯、关注或慈悲。",
    biblicalDiagnosis: "缺乏爱是从有代价的怜悯中退缩，忘记了基督向无助罪人所怀的慈悲。",
    coreLie: "除非方便、安全或情感上有回报，否则我没有责任去爱。",
    gospelTruth: "当我还软弱无助时，基督就爱了我。如今他的爱催逼我走向他人。",
    repentancePrayer: "主啊，我承认我的爱渐渐冷淡，我回避有代价的怜悯。求你用你的慈爱软化我的心，教我用行为和诚实去爱。",
    commonSymptoms: ["对苦难漠不关心", "回避有需要的人", "情感上的退缩", "缺少祷告的负担", "自我保护式的孤立", "对别人的软弱感到烦躁"],
    deepIdols: ["安逸", "情感上的安全", "方便", "自我保护"],
    putOffActions: ["不再忽视显而易见的需要。", "不再以忙碌作为缺乏爱的借口。", "不再轻看软弱。"],
    putOnActions: ["向一个有需要的人走近。", "带着怜悯祷告。", "操练实际的怜悯。"],
  },
  entertainment_escapism: {
    name: "娱乐逃避", shortName: "逃避",
    description: "用娱乐、数字刺激、忙碌或分心来逃避神、现实、痛苦、责任或心灵的空虚。",
    biblicalDiagnosis: "逃避主义要刺激给予安息与生命，却回避祷告、静默、责任和诚实的哀恸。",
    coreLie: "分心娱乐能给我唯有神才能给的安息、安慰与生命。",
    gospelTruth: "神自己是我的避难所与安息。我不需要靠无尽的刺激才有安全感。",
    repentancePrayer: "主啊，我承认我常常逃进分心娱乐，而不来到你面前。教我安静，领受真正的安息，与你一同面对人生。",
    commonSymptoms: ["无尽地刷手机", "回避祷告", "深夜沉迷娱乐", "情感的麻木", "拖延", "害怕安静"],
    deepIdols: ["安逸", "刺激", "逃避", "掌控", "逃避痛苦"],
    putOffActions: ["停止用屏幕逃避神。", "停止深夜的数字逃避。", "停止用刺激取代祷告。"],
    putOnActions: ["操练静默。", "在娱乐之前先读经。", "设立数字界限。"],
  },
  babel_pride: {
    name: "巴别式的科技与文明骄傲", shortName: "巴别",
    description: "信靠人的成就、科技、制度、文明或智慧为拯救者，并寻求脱离神为自己扬名。",
    biblicalDiagnosis: "巴别式的骄傲信靠人的成就与科技为拯救者，为扬名而建造，而非倚靠神。",
    coreLie: "人的能力、科技与成就，能不靠神就保障我们的未来、给我们荣耀。",
    gospelTruth: "若不是耶和华建造房屋，建造的人就枉然劳力。",
    repentancePrayer: "主啊，我承认我倚靠人的能力、科技和成就过于倚靠你。教我只在你的主权之下、为你的荣耀而建造。",
    commonSymptoms: ["科技救世主心态", "执迷于规模与名声", "把效率当作终极", "因工具看似足够而忽略祷告", "把身份建立在成就上"],
    deepIdols: ["科技的力量", "人类的进步", "名声", "掌控", "不朽", "成就"],
    putOffActions: ["停止把工具当作拯救者。", "停止为个人的荣耀而建造。", "停止在计划中忽略祷告。"],
    putOnActions: ["把计划交托给神。", "为服事而非扬名而建造。", "在执行之前先操练倚靠。"],
  },
  spiritual_numbness: {
    name: "属灵麻木", shortName: "苏醒",
    description: "藉着反复的抗拒、分心、妥协或不信，失去对神、圣经、罪、永恒和圣灵责备的敏感。",
    biblicalDiagnosis: "属灵麻木使良心迟钝、拖延顺服、把罪正常化，并把神的声音当作可有可无。",
    coreLie: "保持属灵的迟钝、拖延或冷淡是安全的。",
    gospelTruth: "你们今日若听他的话，就不可硬着心。基督管教他所爱的，并呼召他们回转。",
    repentancePrayer: "圣灵啊，求你苏醒我的心。我承认我的迟钝、拖延和抗拒。求你恢复我对主的敬畏、对你话语的敏锐和迅速的顺服。",
    commonSymptoms: ["罪不再使我忧伤。", "圣经感觉与我无关。", "祷告感觉没有必要。", "我一再拖延顺服。", "我称恶为善，或把圣洁当作过分。", "我回避圣灵的责备。"],
    deepIdols: ["安逸", "自主", "不信", "拖延的顺服", "随从世界"],
    putOffActions: ["停止拖延已知的顺服。", "停止把罪正常化。", "停止回避责备。"],
    putOnActions: ["顺服下一个清楚的命令。", "回到圣经。", "求神赐一颗柔软的心。"],
  },
};

export const PRACTICE_NAME_ZH = {
  "Morning Surrender Prayer": "晨祷交托", "Evening Examen": "晚间省察",
  "Scripture Meditation": "默想经文", "Confession Prayer": "认罪祷告",
  "Gratitude Practice": "感恩操练", "Hidden Service": "隐秘服事",
  "Digital Boundary": "数字界限", "Accountability Check-in": "问责同行",
  "Morning surrender prayer": "晨祷交托", "One hidden act of service": "一次隐秘的服事",
  "Evening review of self-centered reactions": "晚间省察自我中心的反应",
  "Pause before reacting": "回应前先停顿",
  "Pray: Lord, not my will but Yours": "祷告：主啊，不要照我的意思，只要照你的意思",
  "Ask: Am I protecting my kingdom or seeking God's kingdom?": "自问：我在维护自己的国，还是寻求神的国？",
  "Sabbath reflection on control": "安息日反思掌控欲",
  "Serve someone who cannot repay you": "服事一个无法回报你的人",
  "Share one area of self-rule with accountability": "向同行者分享一处自我作主的领域",
  "Identify one thing you fear losing": "指认一件你害怕失去的事物",
  "Pray a surrender prayer over it": "为它献上交托的祷告",
  "Practice gratitude for God Himself": "为神自己献上感恩",
  "Ask: What am I afraid to lose?": "自问：我害怕失去什么？",
  "Pray Psalm 73:25-26": "祷读诗篇73:25-26",
  "Choose one act of obedience that weakens the idol": "选择一个削弱偶像的顺服行动",
  "Idol audit journal": "偶像省察日志",
  "Worship without asking for outcomes": "不求结果地敬拜",
  "Give away time, money, or attention to loosen attachment": "舍出时间、金钱或关注以松开执着",
  "Gratitude list of three provisions": "列出三样神供应的感恩",
  "Pause before purchase": "购买前先停顿", "Pray before checking finances": "查看财务前先祷告",
  "Wait 24 hours before buying": "购买前等候24小时", "Pray Luke 12:15": "祷读路加福音12:15",
  "Give a small amount to someone in need": "拿出一点给有需要的人",
  "Review spending with prayer": "带着祷告回顾开支", "Practice generosity": "操练慷慨施予",
  "Fast from non-essential shopping": "禁戒非必要的购物",
  "Morning body surrender prayer": "晨祷将身体交托",
  "Remove one temptation gateway": "移除一个试探的入口",
  "Practice seeing people as image-bearers": "操练视人为神形象的承载者",
  "Leave the tempting environment immediately": "立刻离开引诱的环境",
  "Contact accountability partner": "联系问责同行者",
  "Pray 1 Corinthians 6:19-20": "祷读哥林多前书6:19-20",
  "Do a physical reset": "做一次身体的重整（如起身、喝水）",
  "Confession with trusted mature believer if needed": "必要时向可信的成熟信徒认罪",
  "Digital boundary review": "回顾数字界限",
  "Scripture memorization on holiness": "背诵关于圣洁的经文",
  "Pray Philippians 2": "祷读腓立比书第2章",
  "Practice one hidden humility action": "操练一次隐秘的谦卑行动",
  "Ask where I defended my ego today": "省察今天我在哪里维护了自我",
  "Pause before defending yourself": "为自己辩护前先停顿",
  "Say: I may be wrong": "说出：我可能错了",
  "Ask one clarifying question before responding": "回应前先问一个澄清的问题",
  "Invite feedback": "主动邀请别人的反馈",
  "Serve in a low-status task": "在不起眼的任务中服事",
  "Confess pride to God and, if appropriate, to another person": "向神（必要时也向他人）承认骄傲",
  "Truth audit": "诚实省察", "One honest confession to God": "向神作一次诚实的认罪",
  "Speak one truthful sentence you were avoiding": "说出一句你一直回避的真话",
  "Pause before answering": "回答前先停顿", "Choose plain truth": "选择朴实的真话",
  "Say: I need to be honest": "说出：我需要诚实",
  "Review image-management patterns": "回顾经营形象的模式",
  "Confess one hidden area to God": "向神坦白一处隐藏的领域",
  "Practice transparent communication": "操练坦诚的沟通",
  "Bless one difficult person in prayer": "在祷告中祝福一个难相处的人",
  "Delay angry responses": "延迟愤怒的回应", "Examine contempt in the heart": "省察心中的轻蔑",
  "Do not respond for 24 hours if emotionally flooded": "情绪泛滥时24小时内不回应",
  "Pray Romans 12:19": "祷读罗马书12:19",
  "Ask: What would peace require now?": "自问：此刻和睦需要我做什么？",
  "Reconciliation review": "回顾和好的进程", "Forgiveness prayer": "饶恕的祷告",
  "Practice gentle speech": "操练温和的言语",
  "Pray for one vulnerable person or group": "为一个弱势的人或群体祷告",
  "Choose fairness over advantage": "选择公平而非占便宜",
  "Notice one person usually ignored": "留意一个常被忽视的人",
  "Ask: Am I using power to serve or exploit?": "自问：我在用权力服事还是剥削？",
  "Choose the righteous action even if costly": "即使有代价也选择公义的行动",
  "Mercy action": "一次怜悯的行动",
  "Justice audit of work and money": "省察工作与金钱中的公义",
  "Serve someone in need": "服事一个有需要的人",
  "Pray Psalm 139:23-24": "祷读诗篇139:23-24", "Name one hidden motive": "指认一个隐藏的动机",
  "Do one unseen act of obedience": "做一件无人看见的顺服",
  "Ask whether I seek God's approval or people's admiration": "省察我寻求的是神的喜悦还是人的称赞",
  "Choose hidden faithfulness over visible performance": "选择隐秘的忠心而非显眼的表演",
  "Honest confession": "诚实的认罪",
  "Review motives in ministry or religious activity": "回顾事奉或宗教活动中的动机",
  "Ask who needs love from me today": "自问今天谁需要我的爱",
  "Send one encouragement": "送出一句鼓励", "Pray for a suffering person": "为一个受苦的人祷告",
  "When tempted to withdraw, ask what love would require": "想要退缩时，自问爱要求我做什么",
  "Visit, call, or help someone weak or lonely": "探访、致电或帮助一个软弱或孤单的人",
  "Practice mercy giving": "操练怜悯的给予", "Review relational coldness": "回顾关系中的冷漠",
  "Ten minutes of silence": "十分钟的静默",
  "No-screen window before sleep": "睡前一段无屏幕时间",
  "Scripture before scrolling": "刷手机前先读经",
  "Put phone away physically": "把手机放到看不见的地方",
  "Set a 10-minute prayer timer": "设10分钟祷告计时",
  "Read one Psalm aloud": "出声朗读一篇诗篇",
  "Digital Sabbath block": "一段数字安息时间", "Review screen time": "回顾屏幕使用时间",
  "Replace one entertainment block with worship or service": "用敬拜或服事替换一段娱乐时间",
  "Pray before work": "工作前先祷告",
  "Ask if this is for God's glory or my name": "自问这是为神的荣耀还是为自己扬名",
  "Practice one limit against productivity idolatry": "操练一个抵挡效率崇拜的界限",
  "Pause when ambition becomes restless": "当野心变得焦躁时停下来",
  "Pray Psalm 127:1": "祷读诗篇127:1",
  "Ask what obedience looks like, not just optimization": "思想顺服是什么，而不只是优化",
  "Review ambition before God": "在神面前省察野心",
  "Sabbath from productivity": "从生产力中安息",
  "Serve someone without strategic benefit": "服事一个对你毫无策略益处的人",
  "Pray for conviction": "祈求圣灵的光照与责备",
  "Read a warning passage slowly": "缓慢读一段警戒的经文",
  "Do one immediate obedience action": "立刻做一个顺服的行动",
  "Say aloud: Today, I will not harden my heart": "出声宣告：今天我不硬着心",
  "Contact a mature believer if numbness persists": "若麻木持续就联系一位成熟信徒",
  "Remove one compromise": "除掉一处妥协", "Extended confession": "一段较长的认罪",
  "Accountability conversation": "一次问责的对话", "Review delayed obedience": "回顾被拖延的顺服",
};

export const PHRASE_ZH = {
  // 引擎情绪谎言 / Emotion-rule lies
  "I must be in control to be safe.": "我必须掌控一切才安全。",
  "God may not provide what I need.": "神也许不会供应我所需要的。",
  "If I lose this, I cannot be okay.": "如果失去这个，我就无法好起来。",
  "I have the right to punish.": "我有权惩罚。",
  "My will must be honored.": "我的意愿必须被尊重。",
  "Contempt will protect me.": "轻蔑能保护我。",
  "God has been better to them than to me.": "神待他们比待我更好。",
  "My worth depends on having what they have.": "我的价值取决于拥有他们所拥有的。",
  "I cannot rejoice unless I am above others.": "除非我高人一等，否则我无法喜乐。",
  "This desire can satisfy me.": "这欲望能满足我。",
  "My body belongs to me.": "我的身体属于我自己。",
  "Secret pleasure will heal my emptiness.": "隐秘的快感能医治我的空虚。",
  "Distraction can fill me.": "分心娱乐能填满我。",
  "God is not enough right now.": "此刻神还不够。",
  "I cannot face silence.": "我无法面对安静。",
  "I must hide to be safe.": "我必须隐藏才安全。",
  "If I am known, I will be rejected.": "如果被人认识，我就会被弃绝。",
  "Appearance matters more than truth.": "外表比真相更重要。",
  "I do not need correction.": "我不需要被纠正。",
  "My wisdom is sufficient.": "我的智慧已经足够。",
  "My achievements prove my worth.": "我的成就证明我的价值。",
  "Delayed obedience is safe.": "拖延顺服是安全的。",
  "This sin is not serious.": "这罪并不严重。",
  "I can return to God later.": "我可以以后再回到神面前。",
  // 牧养提示 / Pastoral notes
  "This may be a moment to bring your restlessness to God instead of escaping into stimulation. Do not begin with self-hatred. Begin by returning to Christ and choosing one small act of stillness.": "也许此刻是把你的烦躁带到神面前、而非逃进刺激的时机。不要以自我厌恶开始，而要从回到基督、选择一个安静的小举动开始。",
  "This may be an invitation to examine where money or possession has become a false refuge. God is not against wise provision, but He calls your heart to trust Him above wealth.": "也许这是一个邀请，去省察金钱或财物在哪里成了虚假的避难所。神并不反对智慧的预备，但他呼召你的心去信靠他过于钱财。",
  "This anger may need to be brought into the light before it becomes contempt. Christ invites you to entrust justice to God and practice one step toward peace.": "这愤怒也许需要在变成轻蔑之前被带到光中。基督邀请你把伸冤交托给神，并迈出一步走向和睦。",
  "This may indicate a pattern worth bringing before God in prayer. The app cannot diagnose your heart with certainty, but it can help you come into the light and choose one concrete act of obedience.": "这也许指向一个值得在祷告中带到神面前的模式。本应用无法确切判断你的内心，但它能帮助你来到光中，并选择一个具体的顺服行动。",
  // 果子鼓励 / Fruit encouragement
  "This is a sign of grace. You are asking the Holy Spirit to form Christlike life in this area.": "这是恩典的记号。你正在求圣灵在这一领域里塑造基督的生命。",
  "Ask for grace here without shame. Fruit is formed by the Spirit, not earned as a badge.": "在这里不带羞耻地祈求恩典。果子是圣灵所结的，不是靠努力换来的勋章。",
  // 每周回顾鼓励 / Weekly encouragement
  "God is bringing this pattern into the light. Do not despise small beginnings. Awareness, confession, and one act of obedience are real signs of grace.": "神正把这个模式带到光中。不要轻看微小的开始。觉察、认罪和一个顺服的行动，都是恩典真实的记号。",
  "No entries yet. Begin with a simple daily scan. The goal is not perfection, but bringing life before God honestly.": "还没有记录。从一次简单的每日省察开始。目标不是完美，而是诚实地把生活带到神面前。",
  // 牧养安全提示 / Pastoral safety
  "If you are in immediate danger or may harm yourself or someone else, contact emergency services now. Please also reach out to a trusted person, pastor, counselor, or medical professional.": "如果你正处于即时危险，或可能伤害自己或他人，请立刻联系紧急救援服务。也请向你信任的人、牧者、辅导员或医疗专业人士求助。",
  "This repeated pattern may need stronger boundaries and real accountability. Please consider speaking with a trusted mature believer, pastor, counselor, or accountability partner.": "这种反复出现的模式可能需要更强的界限和真实的问责。请考虑找一位可信的成熟信徒、牧者、辅导员或问责同行者倾谈。",
  // 免责声明与恩典宣告 / Disclaimer & grace statement
  "This tool is a spiritual formation aid. It does not replace Scripture, prayer, the Holy Spirit, the local church, pastoral care, wise accountability, or professional help when needed.": "本工具是属灵塑造的辅助。它不能取代圣经、祷告、圣灵、地方教会、牧养关怀、智慧的问责，以及在需要时寻求专业帮助。",
  "In Christ, confession is not the end of your story. It is the doorway back into the light.": "在基督里，认罪不是你故事的终点，而是重回光中的门。",
  // 计划回顾问题 / Plan review questions
  "Which sin pattern appeared most often?": "哪个罪的模式出现得最频繁？",
  "What emotion usually came before it?": "通常在它之前出现的是什么情绪？",
  "What trigger usually activated it?": "通常是什么触发点激发了它？",
  "What lie did I believe?": "我相信了什么谎言？",
  "Where did I see God's grace?": "我在哪里看见了神的恩典？",
  "What did I put off this week?": "这一周我脱去了什么？",
  "What did I put on this week?": "这一周我穿上了什么？",
  "When did temptation become strongest?": "试探在何时变得最强？",
  "What boundary needs strengthening?": "哪一道界限需要加强？",
  "What fruit is beginning to appear?": "什么果子开始显现？",
  "Month 1: where did awareness and confession increase?": "第1个月：觉察与认罪在哪里增加了？",
  "Month 2: what boundaries helped mortification?": "第2个月：哪些界限帮助了治死己罪？",
  "Month 3: what new obedience and fruit are becoming more natural?": "第3个月：哪些新的顺服与果子变得更自然？",
  "Which relationships show fruit?": "哪些关系显出果子？",
  "Where do I still resist God?": "我在哪里仍然抗拒神？",
  "Quarter 1: where is holiness and self-control needed?": "第1季度：哪里需要圣洁与节制？",
  "Quarter 2: where is humility and obedience needed?": "第2季度：哪里需要谦卑与顺服？",
  "Quarter 3: where is love, mercy, and compassion needed?": "第3季度：哪里需要爱、怜悯与慈悲？",
  "Quarter 4: where is justice, faithfulness, and worship needed?": "第4季度：哪里需要公义、信实与敬拜？",
  "What next formation theme is God bringing into the light?": "神正把下一个塑造的主题带到光中——是什么？",
  // 建议的下一步 / Recommended next step
  "Invite real accountability today and remove access to the strongest trigger.": "今天就邀请真实的问责，并切断接触最强触发点的途径。",
  "Begin with today's Scripture, confession, and one concrete obedience action.": "从今天的经文、认罪，以及一个具体的顺服行动开始。",
};
