// Mission OS 全功能版开发路线图（Batch 0–5）
// 结构化规划内容，供「宣教」子标签内可折叠路线图页面渲染。
// 每个 Batch 包含：目标、统一原则、Skill 列表（目标 + 关键规则/交付物）。
// 完整 Codex 执行 Prompt 见 docs/mission-os 参考文档。

export const ROADMAP_META = {
  title: 'Mission OS 全功能版',
  subtitle: '禾场情报 → 呼召辨识 → 工人装备 → 教会差派 → 团队建设 → 合法进入 → 在地服事 → 工人关怀 → 本地领袖 → 权力移交 → 全球宣教基础设施',
  dod: [
    '领域模型', '数据库迁移', 'Repository / Service', 'API', '权限策略',
    '前端页面或组件', '审计策略', '单元测试', '集成测试', 'E2E 测试',
    '文档', '与现有属灵星球模块的集成',
  ],
  stack: {
    Frontend: 'Next.js / React / TypeScript / Tailwind / shadcn/ui / TanStack Query / RHF / Zod / next-intl / PWA',
    Backend: 'FastAPI / Python / Pydantic v2 / SQLAlchemy 2 / Alembic',
    Data: 'PostgreSQL / pgvector / (可选 Neo4j) / RLS / Transactional Outbox',
    AI: 'LangGraph / Provider Adapter / Structured Output / Prompt Registry / Model Run Audit / Human-in-the-loop',
    Testing: 'pytest / Vitest / Playwright / axe-core / Schemathesis',
  },
}

export const BATCHES = [
  {
    id: 0,
    key: 'batch-0',
    title: 'Batch 0：项目总控、架构与安全基线',
    goal: '建立不会因后续扩展而推倒重来的工程和治理底座。',
    status: 'implemented',
    statusLabel: '已基本落地',
    principles: [
      'Mission OS 边界清晰，不重建 Identity OS / Formation Engine 已有功能。',
      'AI 不能做最终决策；本地领袖与当地教会优先。',
      '国内外合规与宗教自由边界明确，所有后续 Skill 引用统一宪章。',
    ],
    skills: [
      { id: 0, title: 'Skill 00 · 全项目总宪章与完成定义', body: '**目标**：建立业务边界、伦理底线、技术原则、模块关系和最终完成标准。\n\n**关键交付**：\n- `docs/mission-os/` 宪章、边界、伦理、安全、完成定义、路线图、术语表\n- ADR-001 边界 / 002 数据隔离 / 003 AI 人工复核 / 004 本地教会优先 / 005 敏感字段\n- 伦理宪章：宗教参与自愿、公益与信仰分开、不以物资换宗教、不隐藏机构信仰身份、不宣告个人呼召' },
      { id: 1, title: 'Skill 01 · 现有仓库审计与模块复用分析', body: '**目标**：生成真实仓库地图，避免凭想象开发。\n\n**关键交付**：`repository-audit.md` / `reuse-matrix.md` / `integration-map.md` / `repository-capabilities.json` + 校验脚本；技术债 P0–P3 分级。' },
      { id: 2, title: 'Skill 02 · 领域边界与上下文映射', body: '**Mission OS 自有聚合根**：MissionField、CallingJourney、WorkerReadinessAssessment、SendingJourney、MissionTeam、DeploymentPlan、MemberCarePlan、MissionIncident 等。\n\n**外部模块（通过 Adapter）**：User、IdentityProfile、GiftProfile、FormationPlan、HabitPlan、CrisisCase、ContentItem。\n\n子域不得直接读取其他 Bounded Context 数据库表；架构规则由自动测试保护。' },
      { id: 3, title: 'Skill 03 · Monorepo 模块、依赖方向与代码规范', body: 'domain 不依赖 framework/db/web/AI；统一错误模型（MISSION_NOT_FOUND / FORBIDDEN / CONFLICT / VALIDATION / POLICY_BLOCKED / REVIEW_REQUIRED / RISK_ESCALATED）；统一分页、时区(UTC)、日志规范；Architecture Lint。' },
      { id: 4, title: 'Skill 04 · Feature Flags、环境配置与版本治理', body: '按 global/tenant/org/program/user/environment 作用域覆盖；高风险模块、未成年人、部署、敏感字段默认关闭；一键紧急关闭；所有变更审计。' },
      { id: 5, title: 'Skill 05 · Domain Event、Outbox 与跨模块集成', body: 'Transactional Outbox：与业务事务同写、消费者幂等、Payload 版本化、Dead-letter；敏感字段用引用 ID 而非全文；后台重试写审计。' },
      { id: 6, title: 'Skill 06 · 审计日志、操作追踪与数据血缘', body: '记录 view_sensitive / approve / export / break_glass / ai_generate 等；只记录变更字段名不记原值；Break-glass 强制二次认证 + 事后审查；数据血缘追踪 AI 报告来源。' },
      { id: 7, title: 'Skill 07 · 宣教伦理、Safeguarding 与风险分级', body: '**风险等级 L0–L3**：L2（严重耗竭/家暴/未成年人疑虑）、L3（自伤他伤/儿童虐待/拘留/战争）。AI 只能建议风险等级、不能关闭事件；L2/L3 全程人工工作流；技术性阻止「以物资换宗教参与」。' },
    ],
  },
  {
    id: 1,
    key: 'batch-1',
    title: 'Batch 1：身份、多租户、权限、隐私与同意',
    goal: '建立个人、教会、差会、团队和合作机构之间的安全数据边界。',
    status: 'partial',
    statusLabel: '部分已有',
    principles: [
      '所有租户业务表含 tenant_id；敏感表启用 RLS；字段级授权。',
      '知情同意可撤回；数据保留/导出/删除/匿名化。',
      '未成年人、监护人与高脆弱群体更高保护标准；敏感导出二次认证审批。',
    ],
    skills: [
      { id: 8, title: 'Skill 08 · 多租户组织模型', body: '个人、教会、差会、训练机构、接收机构、团队、合作机构统一 Organization + Membership 模型，验证状态与治理结构。' },
      { id: 9, title: 'Skill 09 · Mission OS 角色与权限矩阵', body: 'RBAC：候选人、导师、教会审核者、差会、接收 Supervisor、Safeguarding Officer、研究员、平台管理员等角色；后端强制权限检查，不依赖前端隐藏按钮。' },
      { id: 10, title: 'Skill 10 · PostgreSQL RLS 租户隔离', body: '所有敏感表启用 Row-Level Security；回填与孤立数据检查后再启用；跨租户越权测试为硬性验收。' },
      { id: 11, title: 'Skill 11 · 敏感字段分级与字段级授权', body: '字段敏感级 P0–P4；公开 DTO / 研究 DTO / 敏感 DTO 分离；P3/P4 不进普通模型与公开接口。' },
      { id: 12, title: 'Skill 12 · 知情同意与同意撤回系统', body: 'Consent 版本化；AI 使用同意独立；撤回后取消待执行 AI 任务；服务同意与信仰探索同意分离。' },
      { id: 13, title: 'Skill 13 · 数据保留、导出、删除与匿名化', body: 'Retention Policy；用户可导出/删除自己的普通数据；受保护第三方安全备注不进入用户导出；匿名化流程。' },
      { id: 14, title: 'Skill 14 · 未成年人、监护人与高脆弱群体保护', body: '未成年人项目 Feature Flag 默认关闭；监护人同意；未成年人事件仅儿童保护角色可见；照片需监护人同意。' },
      { id: 15, title: 'Skill 15 · 二次认证、敏感导出审批与安全会话', body: 'Step-up Authentication；敏感导出短时链接 + 水印 + 审计 + 自动删除；安全会话与 break-glass。' },
    ],
  },
  {
    id: 2,
    key: 'batch-2',
    title: 'Batch 2：全球宣教禾场情报系统',
    goal: '形成可追溯、可验证、可持续更新的国内及全球禾场知识系统。',
    status: 'planned',
    statusLabel: '规划中',
    principles: [
      '群体自我认同优先；不把人简化为单一宗教标签。',
      '数据事实（Observed Fact / Source Claim / Interpretation / Local Confirmation / AI Hypothesis）分离。',
      '禾场「需要很大」与「当前适合进入」严格分离；敏感地理信息 P0–P4 最小化。',
      '不用军事化/征服式表达；公开地图不含 P3/P4 位置。',
    ],
    skills: [
      { id: 16, title: 'Skill 16 · Mission Field 核心领域模型', body: '支持地理与非地理禾场（城市职业群体、侨民、数字社群、教会内部被忽视群体）；层级/重叠/迁移关系；公开与敏感 DTO 分离；Field 合并保留历史引用。' },
      { id: 17, title: 'Skill 17 · 族群、语言、宗教与地区知识图谱', body: '多对多关系：一个族群多语言/多宗教分布；手语作为正式语言；不由族群推断个人信仰；PostgreSQL 为事实源，Neo4j 为可选投影。' },
      { id: 18, title: 'Skill 18 · 侨民、留学生、移工与人口流动模型', body: '区分 Origin/Host；难民/庇护/无证身份高敏；只记社群级数据；不利用脆弱处境优化转化；支持回流与跨城市连续陪伴。' },
      { id: 19, title: 'Skill 19 · 圣经、音频、手语与母语资源可及性', body: '可及性含语言/媒介/识字/分发/本地使用；「已有翻译」≠「当地可取得」；手语与口述独立建模；资源保存 last_verified_at 与版权。' },
      { id: 20, title: 'Skill 20 · 当地教会成熟度与领袖缺口模型', body: '本地教会参与评估；不建公开教会排行榜；规模/建筑/资金不作主要成熟度指标；领袖缺口来自证据与当地表达；高敏教会严格保护。' },
      { id: 21, title: 'Skill 21 · 禾场需要、机会、进入条件与风险模型', body: 'Need/Opportunity/Asset/Constraint/Risk 分离；社会需要可转介专业服务；高风险不提高优先级；缺法律身份/团队/伙伴不能 Ready to Enter。' },
      { id: 22, title: 'Skill 22 · 资料来源、快照与 Claim-Evidence 系统', body: '重要结论关联 Claim + Evidence；AI 只能创建 ai_candidate；数值必带日期与范围；Snapshot 不可覆盖；支持相反证据与争议。' },
      { id: 23, title: 'Skill 23 · 来源冲突、可信度、时效与数据质量', body: '冲突不被静默覆盖，可「保留两个合理估计」；可信度可解释，不显示伪精确百分比；高影响过期数据阻止错误推荐；AI Candidate 不能冒充事实。' },
      { id: 24, title: 'Skill 24 · 禾场优先级评分与可解释推荐引擎', body: '独立输出 Need / Evidence / Readiness / Risk 四类分数；硬阻塞（无合法路径/无团队/当地反对/数据过低）不可被高 Need 抵消；人口规模、难民身份不主导评分。' },
      { id: 25, title: 'Skill 25 · 中国国内宣教禾场模板', body: '按生活场景（基层双职传道人、平台/运输劳动者、教会受伤者、科技/AI 从业者、听障视障群体等）版本化模板；含合规与禁止事项；实例化后仍需本地确认。' },
      { id: 26, title: 'Skill 26 · 全球重点地区与侨民禾场模板', body: '区域模板仅为研究框架非文化结论；高风险地区默认只开放研究与代祷；不含规避签证/法律方案；后方技术支持角色可不直接布道。' },
      { id: 27, title: 'Skill 27 · 禾场地图、比较、研究工作台与报告系统', body: '地图默认公开聚合、含列表替代与无障碍；比较最多 5 个 Field 且显示日期/可比性；报告含不确定性/冲突/来源；公开发布经隐私与敏感位置检查。' },
    ],
  },
  {
    id: 3,
    key: 'batch-3',
    title: 'Batch 3：呼召辨识、恩赐画像与工人准备度',
    goal: '避免把一次感动直接等同于长期差派呼召。',
    status: 'planned',
    statusLabel: '规划中',
    principles: [
      '呼召辨识不是自动化神谕；AI 不宣告神的个人旨意。',
      '呼召方向 / 角色 / 地点 / 时机分离。',
      '准备度不是属灵价值评分；人工确认多源化。',
      '暂停不等于拒绝，使用非羞耻化语言。',
    ],
    skills: [
      { id: 28, title: 'Skill 28 · 宣教呼召辨识旅程', body: '长期 Journey：感动/异象记为 subjective_impression、不能独立推动差派；Field Interest 与 Calling Orientation 分离；教会反馈与真实本地实践为硬性门禁。' },
      { id: 29, title: 'Skill 29 · 呼召动机、属灵状态与反逃避检查', body: '识别逃避债务/家庭/教会冲突、救星情结、控制倾向；Hard Block 有恢复计划、由人工解除；危机内容接入 Safeguarding；不输出属灵价值总分。' },
      { id: 30, title: 'Skill 30 · 教会、导师、家庭与群体多方确认', body: '多方反馈不简单平均、显示一致与冲突点；配偶反馈独立收集与隐私保护；不因反对判定属灵不足；严重安全问题进 Incident。' },
      { id: 31, title: 'Skill 31 · 工人恩赐、职业、经历与能力画像', body: '通过 Adapter 复用现有恩赐/Identity 模块、不重建；Self Report 与 Verified 分离；短宣不等于长期跨文化经验；健康/家庭不进公开 DTO。' },
      { id: 32, title: 'Skill 32 · 宣教角色分类与岗位能力模型', body: '多元角色（植堂、培训、翻译、技术、关怀、研究、运营、动员），后方角色与前线同等可见；专业/儿童/医疗角色有强制资格与安全门槛；角色版本化。' },
      { id: 33, title: 'Skill 33 · 工人、角色、团队与禾场匹配引擎', body: 'Worker→Role→Field→Opportunity 分层匹配；不输出单一「呼召概率」；缺失数据不当作能力不足；高 Need 不提高个人匹配；用户可拒绝匹配。' },
      { id: 34, title: 'Skill 34 · 工人准备度十五维评估系统', body: '15 维（属灵成熟、圣经神学、教会委身、品格、情绪健康、婚姻家庭、财务、团队、冲突、跨文化谦卑、语言、专业、Safeguarding、法律安全、韧性）；Hard Block 不可绕过；Deployment Candidate 需人工 Panel；单身/女性/残障/内向不自动降级。' },
      { id: 35, title: 'Skill 35 · 暂停、恢复、申诉与重新评估流程', body: '非羞耻化暂停；治疗正文不需上传；原审批人不能独立处理申诉；历史评估不可静默删除；恢复后仍需重新评估。' },
      { id: 36, title: 'Skill 36 · AI 呼召辨识边界、人工复核与模型治理', body: 'AI 可总结/提问/找缺证/匹配草案；不能宣告呼召、批准准备度、解除 Hard Block；Prompt Registry 版本化；红队测试（「上帝是否呼召我去…」等）全部通过。' },
    ],
  },
  {
    id: 4,
    key: 'batch-4',
    title: 'Batch 4：宣教装备、课程、语言文化与本地实习',
    goal: '把准备度差距转化为 6–24 个月的具体训练、实践、督导与人工认证路径。',
    status: 'planned',
    statusLabel: '规划中',
    principles: [
      '知识完成 ≠ 工人预备完成；课程不能取代教会生活。',
      '安全课程不是可选装饰；文化学习不是收集异国知识。',
      'AI 不能完成最终认证。',
    ],
    skills: [
      { id: 37, title: 'Skill 37 · 个性化宣教装备计划生成器', body: '由准备度缺口生成版本化 6–24 月计划；每个 Gap 关联训练/实践模块；Hard Block 不能仅靠课程解除；尊重家庭与现实时间；用户确认后才创建习惯。' },
      { id: 38, title: 'Skill 38 · 圣经宣教神学课程系统', body: '以整本圣经叙事为基础；经文/解释/应用分开；争议主题显示传统差异；仅播放视频不能完成；完成形成可验证 Evidence。' },
      { id: 39, title: 'Skill 39 · 教会论、门徒训练与植堂课程', body: '门训指向本地领袖复制；权力/财务/退出纳入训练；无当地教会参与不能完成植堂高级模块；AI 不能认证植堂能力。' },
      { id: 40, title: 'Skill 40 · 世界宗教与跨宗教沟通课程', body: '用可信一手来源、不制造稻草人；区分经典/民间/个人；对话能力优先于辩论；必修「接受对方拒绝」与宗教自由。' },
      { id: 41, title: 'Skill 41 · 处境化、文化人类学与殖民反思课程', body: '先研究自身文化；观察与判断分离；殖民历史与资源权力进课程；刻板印象受课程与技术双重限制；处境化需本地伙伴参与。' },
      { id: 42, title: 'Skill 42 · 团队生活、冲突处理与权力边界课程', body: '领袖承担更高权力边界训练；不强迫受害者和解；和解≠恢复原职位信任；团队契约含举报与退出机制。' },
      { id: 43, title: 'Skill 43 · 儿童保护、家暴、心理危机与转介课程', body: 'Safeguarding 为角色硬门槛；含人工情景评估、非自动测验；认证有有效期、过期自动停止接触权限；明确专业边界（不诊断、不停药）。' },
      { id: 44, title: 'Skill 44 · 语言学习与文化观察系统', body: '长期场景化；自评/AI/母语者评估分离；L4/L5 需母语者评估；官方语言≠心灵语言；文化观察 Observation 与 Interpretation 分离、需 Local Feedback。' },
      { id: 45, title: 'Skill 45 · 职业能力与真实职业身份预备系统', body: '真实合法职业身份、不生成虚假履历/掩护；受监管职业须核实资格；不同国家资格独立；过期证书无效；宣教热心不替代执业能力。' },
      { id: 46, title: 'Skill 46 · 本地跨文化实习管理系统', body: '出国前先在本地受监督服事；必须有 Host/Supervisor/Safeguarding；明确 Allowed/Prohibited Activities；实习对象拒绝信仰活动不影响服务；真实行为成为 Evidence。' },
      { id: 47, title: 'Skill 47 · 短期观察、探索旅程与长期实习', body: '短期观察不夸大为长期经验；项目须声明 Non-objectives；敏感位置不入普通 DTO；长期实习需语言/团队/当地反馈；完成不自动成为 Deployment Candidate。' },
      { id: 48, title: 'Skill 48 · 导师、督导、训练 Cohort 与同伴学习', body: '导师有资格/容量/期限；不可查看配偶或心理私密数据；用户可申请更换；Cohort 成员不能看他人准备度；结束后权限到期。' },
      { id: 49, title: 'Skill 49 · 课程测验、实践观察与人工阶段认证', body: 'Knowledge/Simulation/Real Practice 证据分离；Rubric 用可观察行为、拒绝「很属灵」模糊评价；高风险能力需多证据 + 第二 Reviewer；Batch 4 不签发 Deployment Approval。' },
    ],
  },
  {
    id: 5,
    key: 'batch-5',
    title: 'Batch 5：差派教会、机构、团队、本地伙伴与正式差派',
    goal: '让工人由教会、机构与接收团队共同差派，而非个人独立行动。',
    status: 'planned',
    statusLabel: '规划中',
    principles: [
      '差派是教会和群体行为；教会确认不是领袖个人授权。',
      '本地伙伴拥有真实否决权；配偶同意不能被形式化。',
      '团队需要完整能力、不追求同质化；批准有有效期和条件。',
      'AI 不能参与最终投票。',
    ],
    skills: [
      { id: 50, title: 'Skill 50 · 差派教会管理与教会确认', body: '真实可验证教会关系与观察期；单一牧者不能独立完成全部确认；含差派后牧养/关怀/回流承诺；确认有有效期与撤销。' },
      { id: 51, title: 'Skill 51 · 宣教机构、接收机构与机构能力管理', body: '机构能力可验证可过期；接收责任具体到 Supervisor/Member Care/安全；不能只接资金不担人员责任；高风险地区须危机与撤离能力。' },
      { id: 52, title: 'Skill 52 · 候选人差派申请与完整性审核', body: '申请绑定角色/禾场/教会/机构/团队；完整性检查不可被候选人绕过；过期 Readiness / Retired Role / 缺当地伙伴阻止进入委员会；核心变化触发新版本。' },
      { id: 53, title: 'Skill 53 · 多方审批、差派委员会与正式决定', body: '委员会有法定人数与利益冲突约束；候选人/AI 不能投票；配偶与当地伙伴意见被正式记录与回应；批准附条件、期限与申诉；批准仅解锁 Batch 6、不等于出发。' },
      { id: 54, title: 'Skill 54 · 宣教团队组建与成员生命周期', body: '邀请/试用/加入/暂停/退出/交接；Team Leader 不能自批；配偶不自动成为成员；退出后访问关闭、非羞耻化；敏感团队用 Alias。' },
      { id: 55, title: 'Skill 55 · 团队角色、能力、容量与缺口分析', body: '从个人能力聚合但不简单相加；识别关键单点故障与权力集中；容量含语言/家庭/休息；Safety Critical 需备份；高 Need 不能绕过团队缺口。' },
      { id: 56, title: 'Skill 56 · 团队契约、神学共识与行为规范', body: '契约约束领袖与成员双方；核心共识与允许差异分开；含当地伙伴权利/申诉/退出；禁止「绝对服从」「禁止退出」等操控条款。' },
      { id: 57, title: 'Skill 57 · 团队冲突模拟、健康评估与申诉机制', body: '团队健康持续监测；小团队匿名限制被诚实说明；投诉调查独立、Leader 不能查对自己的投诉；Critical 健康问题可阻止差派；不作绩效羞辱工具。' },
      { id: 58, title: 'Skill 58 · 本地伙伴发现、尽职调查与合作评估', body: '尽职调查双向；本地伙伴有真实选择与否决权；财务支持不等于控制权；联系人网络严格保护、高风险用 Alias；Partner 状态可暂停/结束。' },
      { id: 59, title: 'Skill 59 · 合作协议、决策权、资源权与退出安排', body: '决策权/数据/资源/知识产权清晰；Safeguarding 不能被财务方否决；数据共享须同时满足协议+权限+个人 Consent；终止后安全交接；不作压制举报工具。' },
      { id: 60, title: 'Skill 60 · 代祷伙伴、支持教会与沟通网络', body: '支持网络分级可见；通讯经隐私与安全审核；代祷/筹款不消费他人苦难；财务支持不购买治理权；危机期间自动暂停预定通讯。' },
    ],
  },
]

export const STATUS_STYLES = {
  implemented: { label: '已基本落地', color: '#34c759', bg: 'rgba(52,199,89,0.14)' },
  partial: { label: '部分已有', color: '#ffb347', bg: 'rgba(255,179,71,0.14)' },
  planned: { label: '规划中', color: '#5ac8fa', bg: 'rgba(90,200,250,0.14)' },
}
