from __future__ import annotations

from .models import GospelPathContext, GospelPathPlan, GospelPathSegment


CANONICAL_ORDER = [
    "creation_order",
    "sin_and_idolatry",
    "uses_of_law",
    "christ_and_atonement",
    "justification_by_faith",
    "adoption",
    "union_with_christ",
    "sanctification_by_spirit",
    "church_community",
    "eschatological_hope",
]


class GospelPathPlanner:
    def select_segments(self, context: GospelPathContext) -> list[str]:
        segments = list(CANONICAL_ORDER)

        if context.preferred_depth.value == "brief":
            segments = [
                "creation_order",
                "sin_and_idolatry",
                "christ_and_atonement",
                "justification_by_faith",
                "union_with_christ",
                "sanctification_by_spirit",
                "eschatological_hope",
            ]

        if context.scrupulosity_risk == "high":
            # Retain law but prevent it from dominating the path.
            segments = [
                "creation_order",
                "sin_and_idolatry",
                "uses_of_law",
                "christ_and_atonement",
                "justification_by_faith",
                "adoption",
                "union_with_christ",
                "sanctification_by_spirit",
                "church_community",
                "eschatological_hope",
            ]

        return segments

    def build(self, context: GospelPathContext) -> GospelPathPlan:
        selected = self.select_segments(context)
        segments = []
        for idx, pack_id in enumerate(selected):
            segments.append(GospelPathSegment(
                segment_id=f"{context.case_id}-{idx+1}",
                doctrine_pack_id=pack_id,
                purpose=f"Apply {pack_id} to {context.presenting_issue}",
                personalized_explanation="Generated by doctrine-aware structured output at runtime.",
                transition=selected[idx+1] if idx+1 < len(selected) else "response",
            ))

        return GospelPathPlan(
            plan_id=f"plan-{context.case_id}",
            case_id=context.case_id,
            segments=segments,
            entry_point=selected[0],
            law_gospel_balance={
                "moralism_risk": "low",
                "cheap_grace_risk": "low",
                "decision": "pending_runtime_validation",
            },
        )
