export const FORMATION_NODE_TYPES = [
  'LIFE_EVENT', 'INTERPRETATION', 'IDENTITY_STATEMENT', 'BELIEF_STATEMENT', 'DESIRE', 'FEAR',
  'EMOTION', 'TEMPTATION', 'CHOICE', 'BEHAVIOR', 'SPIRITUAL_PRACTICE', 'OUTCOME',
  'GRACE_EVIDENCE', 'PROTECTIVE_FACTOR', 'RECOVERY_RESPONSE', 'FORMATION_DIRECTION',
] as const

export const FORMATION_SOURCE_KINDS = ['USER_REPORT', 'OBSERVATION', 'RULE', 'MODEL', 'USER_CONFIRMED'] as const
export const FORMATION_STATEMENT_TYPES = [
  'USER_REPORTED_FACT', 'OBSERVED_EVENT', 'RULE_DERIVED_RELATION',
  'MODEL_EXTRACTED_EXPLICIT_EXPRESSION', 'MODEL_FORMATION_HYPOTHESIS',
  'USER_CONFIRMED_FORMATION_PATTERN',
] as const
export const FORMATION_SCOPES = ['THIS_EVENT_ONLY', 'THIS_SEASON', 'RECURRING_CONTEXT', 'USER_DEFINED'] as const

export type FormationNodeType = typeof FORMATION_NODE_TYPES[number]
export type FormationSourceKind = typeof FORMATION_SOURCE_KINDS[number]
export type FormationStatementType = typeof FORMATION_STATEMENT_TYPES[number]
export type FormationScope = typeof FORMATION_SCOPES[number]
