import { useCallback, useEffect, useState } from 'react'
import { t as i18nT } from '../../i18n/runtime'
import {
  createEmotionalEpisode, deleteEmotionObservation, deleteEmotionalEpisode,
  getEmotionalState, getEmotionSettings, listEmotionCandidates, listEmotionObservations, listEmotionalEpisodes,
  mergeEmotionalEpisodes, rebuildEmotionalState, resolveEmotionalEpisode, reviewEmotionCandidate, splitEmotionalEpisode, updateEmotionSettings,
} from './formationTwinApi'

const VIEWS = [['current', '当前状态'], ['timeline', '情绪时间线'], ['trends', '变化趋势'], ['review', '待确认'], ['episodes', '情感事件'], ['settings', '处理授权']]
const LABELS = { JOY:'喜乐',PEACE:'平安',LOVE:'爱',HOPE:'盼望',GRATITUDE:'感恩',SADNESS:'难过',GRIEF:'哀伤',LONELINESS:'孤单',DISAPPOINTMENT:'失望',HELPLESSNESS:'无助',ANGER:'愤怒',FRUSTRATION:'挫败',IRRITATION:'烦躁',FEAR:'恐惧',ANXIETY:'焦虑',WORRY:'担忧',UNCERTAINTY:'不安',OVERWHELM:'不堪重负',SHAME:'羞耻',GUILT:'内疚',REGRET:'后悔',NUMBNESS:'麻木',CONFUSION:'困惑',MIXED:'混合',UNKNOWN:'无法命名',OTHER:'自定义' }
const SOURCE = { USER_REPORT:'你主动报告',USER_CONFIRMED:'你确认的候选',RULE:'根据记录计算',MODEL:'系统候选，尚待确认' }

function Notice({ error, message }) { return error ? <div className="ft-workspace-error" role="alert">{error}</div> : message ? <div className="ft-workspace-success" role="status">{message}</div> : null }
function SourceBadge({ kind }) { return <span className={`ft-emotion-source ${String(kind).toLowerCase()}`}>{i18nT(SOURCE[kind] || kind)}</span> }

function CurrentView({ refresh }) {
  const [data,setData]=useState(null); const [error,setError]=useState(''); const [busy,setBusy]=useState(false)
  const load=useCallback(async()=>{try{setData((await getEmotionalState('current')).snapshot)}catch(e){setError(e.message)}},[])
  useEffect(()=>{load()},[load,refresh])
  const rebuild=async()=>{setBusy(true);setError('');try{await rebuildEmotionalState();await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
  const emotions=data?.user_reported?.emotions||[]; const bodyStates=data?.user_reported?.body_states||[]; const vitals=data?.user_reported?.latest_energy_stress_sleep
  return <div className="ft-emotion-view"><header className="ft-emotion-view-head"><div><h3>{i18nT('当前情感状态')}</h3><p>{i18nT('以下内容严格区分你的自述、确定性计算和待确认候选。')}</p></div><button type="button" onClick={rebuild} disabled={busy}>{busy?i18nT('正在重建…'):i18nT('按当前授权重建')}</button></header><Notice error={error}/>{!data?<p className="ft-muted">{i18nT('正在加载…')}</p>:data.data_status==='INSUFFICIENT_DATA'?<div className="ft-workspace-empty">{data.limitations?.[0]||i18nT('目前没有可处理的记录。STORE_ONLY 内容不会进入情感引擎。')}</div>:<><section className="ft-emotion-block user"><h4><SourceBadge kind="USER_REPORT"/></h4><div className="ft-emotion-chips">{emotions.map(item=><div key={item.id||`${item.emotion_label}-${item.custom_label||''}`}><strong>{i18nT(LABELS[item.emotion_label]||item.custom_label||item.emotion_label)}</strong>{item.intensity!=null&&<span>{item.intensity}/10</span>}<SourceBadge kind={item.source_kind||'USER_REPORT'}/></div>)}</div>{bodyStates.length>0&&<p>{i18nT('身体感受：')}{bodyStates.map(item=>i18nT(item.body_label)).join('、')}</p>}{vitals&&<div className="ft-vital-grid">{[['energy_level','精力'],['stress_level','压力'],['sleep_quality','睡眠']].map(([key,label])=><div key={key}><span>{i18nT(label)}</span><strong>{vitals[key]??'—'}</strong><small>/10</small></div>)}</div>}</section><section className="ft-emotion-block rule"><h4><SourceBadge kind="RULE"/></h4><div className="ft-trend-grid">{Object.entries(data.rule_derived||{}).filter(([key])=>key.endsWith('_trend')).map(([key,value])=><div key={key}><span>{i18nT(key.replace('_trend',''))}</span><strong>{i18nT(value.direction)}</strong><small>{value.data_points} {i18nT('个记录点')}</small></div>)}</div><p>{i18nT('覆盖率只描述记录完整程度，不代表结论真实性。')}</p></section><section className="ft-emotion-block model"><h4><SourceBadge kind="MODEL"/></h4>{(data.possible_model_candidates||[]).length?<p>{i18nT('这些内容只会出现在待确认区域，不会自动成为你的事实。')}</p>:<p>{i18nT('目前没有待确认的模型候选。')}</p>}</section><div className="ft-limitations">{(data.limitations||[]).map(item=><p key={item}>{i18nT(item)}</p>)}</div></>}</div>
}

function TimelineView({ refresh }) {
  const [items,setItems]=useState([]);const [error,setError]=useState('')
  useEffect(()=>{listEmotionObservations().then(x=>setItems(x.items||[])).catch(e=>setError(e.message))},[refresh])
  const remove=async id=>{try{await deleteEmotionObservation(id);setItems(items.filter(x=>x.id!==id))}catch(e){setError(e.message)}}
  return <div className="ft-emotion-view"><div className="ft-form-intro"><h3>{i18nT('情绪时间线')}</h3><p>{i18nT('时间线展示记录来源；删除或排除后不会继续参与快照。')}</p></div><Notice error={error}/>{items.length?items.map(item=><article className="ft-emotion-timeline-item" key={item.id}><div><SourceBadge kind={item.source_kind}/><time>{new Date(item.occurred_at).toLocaleString()}</time></div><h4>{i18nT(LABELS[item.emotion_label]||item.custom_label||item.emotion_label)} {item.intensity!=null&&`${item.intensity}/10`}</h4><p>{item.statement_type}{item.confidence!=null?` · ${i18nT('候选置信度')} ${Math.round(item.confidence*100)}%`:''}</p>{item.source_kind==='USER_REPORT'&&<button type="button" onClick={()=>remove(item.id)}>{i18nT('删除观察')}</button>}</article>):<div className="ft-workspace-empty">{i18nT('还没有情绪观察。')}</div>}</div>
}

function TrendsView({ refresh }) {
  const [data,setData]=useState(null);const [error,setError]=useState('')
  useEffect(()=>{getEmotionalState('weekly').then(setData).catch(e=>setError(e.message))},[refresh])
  const snapshot=data?.snapshot;return <div className="ft-emotion-view"><div className="ft-form-intro"><h3>{i18nT('最近七天的记录变化')}</h3><p>{i18nT('图表反映的是你的记录，不一定覆盖全部实际经历。')}</p></div><Notice error={error}/>{snapshot?.data_status==='AVAILABLE'?<><div className="ft-frequency-list">{(data.frequencies||[]).map((item)=>{const max=Math.max(...data.frequencies.map(x=>x.recorded_count),1);return <div key={item.emotion_label}><span>{i18nT(LABELS[item.emotion_label]||item.emotion_label)}</span><div><i style={{width:`${item.recorded_count/max*100}%`}}/></div><strong>{item.recorded_count} {i18nT('次记录')}</strong></div>})}</div><p className="ft-coverage-note">{i18nT('数据覆盖率：')}{Math.round((snapshot.data_coverage?.coverage||0)*100)}% · {i18nT('记录频次不等于实际发生频次。')}</p></>:<div className="ft-workspace-empty">{i18nT('数据不足，不显示可能误导的趋势图。')}</div>}</div>
}

function ReviewView({ onChanged }) {
  const [items,setItems]=useState([]);const [label,setLabel]=useState({});const [error,setError]=useState('')
  const load=useCallback(()=>listEmotionCandidates().then(x=>setItems((x.items||[]).filter(i=>i.user_review_status==='PENDING'))).catch(e=>setError(e.message)),[]);useEffect(()=>{load()},[load])
  const act=async(item,action)=>{try{await reviewEmotionCandidate(item.id,action,action==='relabel'||action==='partially-confirm'?{user_label:label[item.id]}:{});await rebuildEmotionalState();await load();onChanged()}catch(e){setError(e.message)}}
  return <div className="ft-emotion-view"><div className="ft-form-intro"><h3>{i18nT('待你确认的可能情绪')}</h3><p>{i18nT('即使候选置信度很高，也只有你能决定它是否符合那次经历。')}</p></div><Notice error={error}/>{items.length?items.map(item=><article className="ft-review-card" key={item.id}><SourceBadge kind="MODEL"/><h4>{i18nT(LABELS[item.emotion_label]||item.emotion_label)}</h4><p>{i18nT('候选置信度')} {Math.round((item.confidence||0)*100)}% · {i18nT('不是事实或诊断')}</p><div><button onClick={()=>act(item,'confirm')}>{i18nT('符合')}</button><button onClick={()=>act(item,'reject')}>{i18nT('不符合')}</button><button onClick={()=>act(item,'dismiss')}>{i18nT('不想回答')}</button></div><label>{i18nT('换一个更贴切的词')}<input value={label[item.id]||''} onChange={e=>setLabel({...label,[item.id]:e.target.value})}/><button disabled={!label[item.id]?.trim()} onClick={()=>act(item,'relabel')}>{i18nT('按我的词保存')}</button></label></article>):<div className="ft-workspace-empty">{i18nT('目前没有等待确认的情绪候选。')}</div>}</div>
}

function EpisodesView({ onChanged }) {
  const [items,setItems]=useState([]);const [title,setTitle]=useState('');const [selected,setSelected]=useState([]);const [splitEvents,setSplitEvents]=useState({});const [error,setError]=useState('')
  const load=useCallback(()=>listEmotionalEpisodes().then(x=>setItems(x.items||[])).catch(e=>setError(e.message)),[]);useEffect(()=>{load()},[load])
  const create=async()=>{try{await createEmotionalEpisode({title,episode_type:'USER_DEFINED',started_at:new Date().toISOString(),life_domains:[],primary_emotions:[],secondary_emotions:[],life_event_ids:[]});setTitle('');await load();onChanged()}catch(e){setError(e.message)}}
  const control=async(item,action)=>{try{if(action==='resolve')await resolveEmotionalEpisode(item.id);else await deleteEmotionalEpisode(item.id);await load();onChanged()}catch(e){setError(e.message)}}
  const merge=async()=>{try{const [first,...rest]=selected;await mergeEmotionalEpisodes(first,rest,title||i18nT('合并后的情感事件'));setSelected([]);setTitle('');await load();onChanged()}catch(e){setError(e.message)}}
  const split=async item=>{try{await splitEmotionalEpisode(item.id,splitEvents[item.id]||[],`${item.title||i18nT('情感事件')} · ${i18nT('拆分')}`);setSplitEvents({...splitEvents,[item.id]:[]});await load();onChanged()}catch(e){setError(e.message)}}
  const toggleEvent=(episodeId,eventId)=>setSplitEvents(current=>{const values=current[episodeId]||[];return {...current,[episodeId]:values.includes(eventId)?values.filter(id=>id!==eventId):[...values,eventId]}})
  return <div className="ft-emotion-view"><div className="ft-form-intro"><h3>{i18nT('情感事件')}</h3><p>{i18nT('Episode 只帮助整理同一件事的记录，不解释其属灵或心理原因。')}</p></div><div className="ft-episode-create"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder={i18nT('例如：这次项目评审')}/><button disabled={!title.trim()} onClick={create}>{i18nT('创建事件')}</button><button disabled={selected.length<2} onClick={merge}>{i18nT('合并所选事件')}</button></div><Notice error={error}/>{items.map(item=><article className="ft-episode-card" key={item.id}><div><label><input type="checkbox" checked={selected.includes(item.id)} onChange={e=>setSelected(e.target.checked?[...selected,item.id]:selected.filter(id=>id!==item.id))}/><strong>{item.title||i18nT('未命名事件')}</strong></label><span>{item.status}</span></div><p>{new Date(item.started_at).toLocaleString()} · {i18nT(item.episode_type)}</p>{item.life_event_ids?.length>1&&<fieldset><legend>{i18nT('选择要拆出的生命事件')}</legend>{item.life_event_ids.map(eventId=><label key={eventId}><input type="checkbox" checked={(splitEvents[item.id]||[]).includes(eventId)} onChange={()=>toggleEvent(item.id,eventId)}/><code>{eventId.slice(0,8)}</code></label>)}<button disabled={!(splitEvents[item.id]||[]).length} onClick={()=>split(item)}>{i18nT('拆分为新事件')}</button></fieldset>}<button onClick={()=>control(item,'resolve')}>{i18nT('标记结束')}</button><button onClick={()=>control(item,'delete')}>{i18nT('删除')}</button></article>)}</div>
}

function SettingsView() {
  const [value,setValue]=useState(null);const [error,setError]=useState('');const [message,setMessage]=useState('')
  useEffect(()=>{getEmotionSettings().then(setValue).catch(e=>setError(e.message))},[])
  const save=async()=>{setError('');try{const data=await updateEmotionSettings(value);setValue(data);setMessage(i18nT('情感处理授权已更新。'))}catch(e){setError(e.message)}}
  if(!value)return <Notice error={error}/>
  return <div className="ft-emotion-view"><div className="ft-form-intro"><h3>{i18nT('情感处理与模型授权')}</h3><p>{i18nT('确定性处理和文本模型推断可以分别关闭；模型默认关闭。')}</p></div><Notice error={error} message={message}/><div className="ft-setting-list"><label><input type="checkbox" checked={value.emotion_engine_enabled} onChange={e=>setValue({...value,emotion_engine_enabled:e.target.checked})}/><span><strong>{i18nT('处理允许分析的主动记录')}</strong><small>{i18nT('STORE_ONLY、删除和排除事件始终不处理')}</small></span></label><label><input type="checkbox" checked={value.trends_enabled} onChange={e=>setValue({...value,trends_enabled:e.target.checked})}/><span><strong>{i18nT('显示确定性趋势')}</strong><small>{i18nT('只计算记录变化，不生成健康分')}</small></span></label><label><input type="checkbox" checked={value.model_inference_enabled} onChange={e=>setValue({...value,model_inference_enabled:e.target.checked,provider_policy:e.target.checked?'CLOUD_PROVIDER':'DISABLED'})}/><span><strong>{i18nT('允许文本情绪候选')}</strong><small>{i18nT('候选需要你确认，不用于训练共享模型')}</small></span></label></div><button className="ft-submit" onClick={save}>{i18nT('保存授权')}</button></div>
}

export default function FormationTwinEmotions(){const [view,setView]=useState('current');const [refresh,setRefresh]=useState(0);const changed=()=>setRefresh(x=>x+1);return <div className="ft-emotions"><div className="ft-emotion-tabs" role="tablist">{VIEWS.map(([key,label])=><button type="button" role="tab" aria-selected={view===key} key={key} onClick={()=>setView(key)}>{i18nT(label)}</button>)}</div>{view==='current'&&<CurrentView refresh={refresh}/>} {view==='timeline'&&<TimelineView refresh={refresh}/>} {view==='trends'&&<TrendsView refresh={refresh}/>} {view==='review'&&<ReviewView onChanged={changed}/>} {view==='episodes'&&<EpisodesView onChanged={changed}/>} {view==='settings'&&<SettingsView/>}</div>}
