import { API_BASE } from './api'

async function request(path, token, options = {}) {
  const response = await fetch(`${API_BASE}/mission-bridge${path}`, {
    credentials: 'include',
    ...options,
    headers: {
      ...(options.body ? { 'Content-Type': 'application/json' } : {}),
      ...(token ? { Authorization: `Bearer ${token}` } : {}),
      ...options.headers,
    },
  })
  const data = await response.json().catch(() => ({}))
  if (!response.ok) throw new Error(typeof data.detail === 'string' ? data.detail : 'MissionBridge 服务暂时不可用')
  return data
}

export const fetchMissionBridgeDashboard = (token) => request('/dashboard', token)
export const updateMissionBridgeConsent = (token, consentType, granted) => request('/consents', token, { method: 'PUT', body: JSON.stringify({ consentType, granted, policyVersion: '1.0.0' }) })
export const enrollMissionBridgeProgram = (token, programId, participantGoal) => request('/enrollments', token, { method: 'POST', body: JSON.stringify({ programId, participantGoal }) })
export const exitMissionBridgeProgram = (token, enrollmentId) => request(`/enrollments/${enrollmentId}/exit`, token, { method: 'POST' })
export const submitMissionBridgeCheckin = (token, enrollmentId, payload) => request(`/enrollments/${enrollmentId}/checkins`, token, { method: 'POST', body: JSON.stringify(payload) })
export const reportMissionBridgeIncident = (token, payload) => request('/incidents', token, { method: 'POST', body: JSON.stringify(payload) })
export const fetchMissionBridgePolicy = (token) => request('/policy', token)
export const acknowledgeMissionBridgePolicy = (token) => request('/policy/acknowledge', token, { method: 'POST' })
export const fetchMissionBridgeIncidents = (token) => request('/admin/incidents', token)
export const resolveMissionBridgeIncident = (token, incidentId, resolutionNote) => request(`/admin/incidents/${incidentId}/resolve`, token, { method: 'POST', body: JSON.stringify({ resolutionNote }) })
export const fetchMissionBridgeConsents = (token) => request('/privacy/consents', token)
export const updateMissionBridgeDetailedConsent = (token, consentType, granted) => request(`/privacy/consents/${consentType}`, token, { method: 'PUT', body: JSON.stringify({ granted, language: 'zh-CN' }) })
export const requestMissionBridgeExport = (token) => request('/privacy/export', token, { method: 'POST' })
export const requestMissionBridgeDeletion = (token) => request('/privacy/delete', token, { method: 'POST' })
export const fetchMissionBridgeProposals = (token) => request('/discovery/proposals', token)
export const createMissionBridgeProposal = (token, payload) => request('/discovery/proposals', token, { method: 'POST', body: JSON.stringify(payload) })
export const fetchMissionBridgeDiscoveryReport = (token, proposalId) => request(`/discovery/proposals/${proposalId}/report`, token)
export const validateMissionBridgeProgram = (token, definition) => request('/admin/programs/validate', token, { method: 'POST', body: JSON.stringify({ definition }) })
export const publishMissionBridgeProgram = (token, definition) => request('/admin/programs/publish', token, { method: 'POST', body: JSON.stringify({ definition }) })
export const pauseMissionBridgeProgram = (token, enrollmentId) => request(`/enrollments/${enrollmentId}/pause`, token, { method: 'POST' })
export const resumeMissionBridgeProgram = (token, enrollmentId) => request(`/enrollments/${enrollmentId}/resume`, token, { method: 'POST' })
export const fetchMissionBridgeJourney = (token) => request('/journey', token)
export const createMissionBridgeGoal = (token, payload) => request('/journey/goals', token, { method: 'POST', body: JSON.stringify(payload) })
export const confirmMissionBridgeGoal = (token, goalId) => request(`/journey/goals/${goalId}/confirm`, token, { method: 'POST' })
export const completeMissionBridgeAction = (token, actionId) => request(`/journey/actions/${actionId}/complete`, token, { method: 'POST' })
export const fetchMissionBridgeTraining = (token) => request('/training/dashboard', token)
export const createMissionBridgeCohort = (token, payload) => request('/training/cohorts', token, { method: 'POST', body: JSON.stringify(payload) })
export const saveMissionBridgeMentor = (token, payload) => request('/training/mentors', token, { method: 'POST', body: JSON.stringify(payload) })
export const assignMissionBridgeMentor = (token, payload) => request('/training/mentor-assignments', token, { method: 'POST', body: JSON.stringify(payload) })
export const submitMissionBridgeTrainerCandidate = (token, payload) => request('/training/trainer-candidates', token, { method: 'POST', body: JSON.stringify(payload) })
export const decideMissionBridgeTrainer = (token, candidateId, payload) => request(`/training/trainer-candidates/${candidateId}/decision`, token, { method: 'POST', body: JSON.stringify(payload) })
export const fetchMissionBridgeContentLibrary = (token) => request('/content/library', token)
export const searchMissionBridgeContent = (token, query) => request(`/content/rag?q=${encodeURIComponent(query)}`, token)
export const createMissionBridgeContent = (token, payload) => request('/content/items', token, { method: 'POST', body: JSON.stringify(payload) })
export const verifyMissionBridgeContentSource = (token, sourceId) => request(`/content/sources/${sourceId}/verify`, token, { method: 'POST' })
export const reviewMissionBridgeContent = (token, versionId, payload) => request(`/content/versions/${versionId}/reviews`, token, { method: 'POST', body: JSON.stringify(payload) })
export const publishMissionBridgeContent = (token, versionId) => request(`/content/versions/${versionId}/publish`, token, { method: 'POST' })
export const fetchMissionBridgeAgentCatalog = (token) => request('/agents/catalog', token)
export const runMissionBridgeAgent = (token, payload) => request('/agents/runs', token, { method: 'POST', body: JSON.stringify(payload) })
export const fetchMissionBridgeAgentHistory = (token) => request('/agents/runs', token)
export const reviewMissionBridgeAgentRun = (token, runId, payload) => request(`/agents/runs/${runId}/reviews`, token, { method: 'POST', body: JSON.stringify(payload) })
export const fetchLocalLeaderDashboard = (token) => request('/pilots/local-leader/dashboard', token)
export const saveLocalLeaderObservation = (token, payload) => request('/pilots/local-leader/observations', token, { method: 'POST', body: JSON.stringify(payload) })
export const saveLocalLeaderWeeklyReview = (token, payload) => request('/pilots/local-leader/weekly-reviews', token, { method: 'POST', body: JSON.stringify(payload) })
export const createLocalLeaderApprentice = (token, payload) => request('/pilots/local-leader/apprentices', token, { method: 'POST', body: JSON.stringify(payload) })
export const fetchAttentionPilotDashboard = (token) => request('/pilots/attention-reset/dashboard', token)
export const saveAttentionPilotTrigger = (token, payload) => request('/pilots/attention-reset/triggers', token, { method: 'POST', body: JSON.stringify(payload) })
export const startAttentionPilotRecovery = (token, payload) => request('/pilots/attention-reset/recovery', token, { method: 'POST', body: JSON.stringify(payload) })
export const fetchAiFaithDashboard = (token) => request('/pilots/ai-faith/dashboard', token)
export const submitAiFaithQuestion = (token, payload) => request('/pilots/ai-faith/questions', token, { method: 'POST', body: JSON.stringify(payload) })
export const requestAiFaithFollowup = (token, payload) => request('/pilots/ai-faith/followups', token, { method: 'POST', body: JSON.stringify(payload) })
export const saveAiFaithLearning = (token, payload) => request('/pilots/ai-faith/learning', token, { method: 'POST', body: JSON.stringify(payload) })
export const fetchMobileWorkerDashboard = (token) => request('/modules/mobile-workers/dashboard', token)
export const updateMobileWorkerProfile = (token, payload) => request('/modules/mobile-workers/profile', token, { method: 'PUT', body: JSON.stringify(payload) })
export const updateMobileWorkerAudioProgress = (token, audioId, payload) => request(`/modules/mobile-workers/audio/${audioId}/progress`, token, { method: 'PUT', body: JSON.stringify(payload) })
export const requestMobileWorkerCallback = (token) => request('/modules/mobile-workers/callback', token, { method: 'POST' })
export const fetchNightShiftDashboard = (token) => request('/modules/night-shift/dashboard', token)
export const updateNightShiftProfile = (token, payload) => request('/modules/night-shift/profile', token, { method: 'PUT', body: JSON.stringify(payload) })
export const createNightShiftCheckin = (token, payload) => request('/modules/night-shift/checkins', token, { method: 'POST', body: JSON.stringify(payload) })
export const createNightShiftDebrief = (token, payload) => request('/modules/night-shift/debriefs', token, { method: 'POST', body: JSON.stringify(payload) })
export const fetchMobileFamilyDashboard = (token) => request('/modules/mobile-families/dashboard', token)
export const updateMobileFamilyHousehold = (token, payload) => request('/modules/mobile-families/household', token, { method: 'PUT', body: JSON.stringify(payload) })
export const createMobileFamilyChild = (token, payload) => request('/modules/mobile-families/children', token, { method: 'POST', body: JSON.stringify(payload) })
export const createMobileFamilyTask = (token, payload) => request('/modules/mobile-families/tasks', token, { method: 'POST', body: JSON.stringify(payload) })
export const fetchElderCaregiverDashboard = (token) => request('/modules/elder-caregivers/dashboard', token)
export const createElderCaregiverAssessment = (token, payload) => request('/modules/elder-caregivers/assessments', token, { method: 'POST', body: JSON.stringify(payload) })
export const requestElderCaregiverRespite = (token, payload) => request('/modules/elder-caregivers/respite', token, { method: 'POST', body: JSON.stringify(payload) })
export const fetchMentalHealthFamilyDashboard = (token) => request('/modules/mental-health-families/dashboard', token)
export const createMentalHealthReminder = (token, payload) => request('/modules/mental-health-families/reminders', token, { method: 'POST', body: JSON.stringify(payload) })
export const createMentalHealthWarning = (token, payload) => request('/modules/mental-health-families/warnings', token, { method: 'POST', body: JSON.stringify(payload) })
export const fetchAccessibilityPreferences = (token) => request('/accessibility/preferences', token)
export const saveAccessibilityPreferences = (token, payload) => request('/accessibility/preferences', token, { method: 'PUT', body: JSON.stringify(payload) })
export const fetchChurchHarmDashboard = (token) => request('/modules/church-harm/dashboard', token)
export const saveChurchHarmProfile = (token, payload) => request('/modules/church-harm/profile', token, { method: 'PUT', body: JSON.stringify(payload) })
export const submitChurchHarmComplaint = (token, payload) => request('/modules/church-harm/complaints', token, { method: 'POST', body: JSON.stringify(payload) })
export const fetchFamilyTransitionDashboard = (token) => request('/modules/family-transitions/dashboard', token)
export const saveFamilyTransitionProfile = (token, payload) => request('/modules/family-transitions/profile', token, { method: 'PUT', body: JSON.stringify(payload) })
export const saveFamilyTransitionGrief = (token, payload) => request('/modules/family-transitions/grief', token, { method: 'POST', body: JSON.stringify(payload) })
export const fetchMinistryFamilyDashboard = (token) => request('/modules/ministry-families/dashboard', token)
export const saveMinistryFamilyProfile = (token, payload) => request('/modules/ministry-families/profile', token, { method: 'PUT', body: JSON.stringify(payload) })
export const fetchTransitionYouthDashboard = (token) => request('/modules/transition-youth/dashboard', token)
export const createTransitionYouthProfile = (token, payload) => request('/modules/transition-youth/profiles', token, { method: 'POST', body: JSON.stringify(payload) })
export const fetchReentryDashboard = (token) => request('/modules/reentry/dashboard', token)
export const saveReentryProfile = (token, payload) => request('/modules/reentry/profile', token, { method: 'PUT', body: JSON.stringify(payload) })
export const saveReentryFaithChoice = (token, payload) => request('/modules/reentry/faith-choice', token, { method: 'POST', body: JSON.stringify(payload) })
export const fetchMissionBridgeOperations = (token) => request('/operations/dashboard', token)
export const fetchMissionBridgeParticipants = (token) => request('/operations/participants', token)
export const fetchMissionBridgeOutcomes = (token) => request('/outcomes/dashboard', token)
export const fetchMissionBridgeAnalyticsCatalog = (token) => request('/analytics/catalog', token)
