import { create } from 'zustand'

export const useEmotionStore = create((set) => ({
  layoutItems: [],
  historyItems: [],
  hovered: null,
  selectedFeature: null,
  selectedFeatureDetail: null,
  sphereGuidance: null,
  sphereBiblicalExample: null,
  sphereLoading: false,
  queryResult: null,
  languageFilter: 'cuv',
  topFeatures: 6,
  topVerses: 5,
  zoomLevel: 'far',
  communityHeatmap: [],   // [{label, count, pct, colour}, ...]
  loading: false,
  error: '',
  setLayoutItems: (layoutItems) => set({ layoutItems }),
  setHistoryItems: (historyItems) => set({ historyItems }),
  setHovered: (hovered) => set({ hovered }),
  setSelectedFeature: (selectedFeature) => set({ selectedFeature }),
  setSelectedFeatureDetail: (selectedFeatureDetail) => set({ selectedFeatureDetail }),
  setSphereGuidance: (sphereGuidance) => set({ sphereGuidance }),
  setSpheresBiblicalExample: (sphereBiblicalExample) => set({ sphereBiblicalExample }),
  setSphereLoading: (sphereLoading) => set({ sphereLoading }),
  setQueryResult: (queryResult) => set({ queryResult }),
  setLanguageFilter: (languageFilter) => set({ languageFilter }),
  setTopFeatures: (topFeatures) => set({ topFeatures }),
  setTopVerses: (topVerses) => set({ topVerses }),
  setZoomLevel: (zoomLevel) => set({ zoomLevel }),
  setCommunityHeatmap: (communityHeatmap) => set({ communityHeatmap }),
  setLoading: (loading) => set({ loading }),
  setError: (error) => set({ error }),
}))
